easy_admin:
    user:

        display_name: false
        display_avatar: true
    site_name: 'Management des salon de coiffure'
    design:
        menu:

            - label: "Coiffeur"
              children:
                  - {entity: Coif, label: "list de Coiffeur", icon: "th-list"}
                  - {entity: Coif, label: "Ajouter Coiffeur", icon: "plus", params: {action: 'new'}}
    entities:
        Coif:
            class: App\Entity\Coif
            label: "Coiffeur"
            form:
                fields:
                    - NomPro
                    - PrenomPro
                    - NomSalon
                    - NombreChaise
                    - Ville
                    - Description
                    - PhotoCoif
                    - Publish
            list:
                collapse_actions: true
                actions: ['show', 'edit', 'delete']
                batch_actions: ['delete']
                filters: ['Publish','Ville','NombreChaise']




        # List the entity class name you want to manage
        # - App\Entity\User
        #- App\Entity\Coif
        #- App\Entity\Client
